# EDITA estos valores con los de tu servidor SMTP

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.username=yojeidymorfe740@gmail.com
mail.password=trrr ebml enhz jsif
mail.from=yojeidymorfe740@gmail.com

# mail.username=anneidygrullon0120@gmail.com
# mail.password=Anne011820
# mail.from=anneidygrullon0120@gmail.com
mail.from.name=Factory Rent Car
